---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CLUSTER_NAME
  region: REGION_CODE
  version: '1.31'

iam:
  withOIDC: true

managedNodeGroups:
  - name: NODE_GROUP_NAME
    instanceTypes: ["m6a.metal", "m7a.metal-48xl"]
    spot: true
    overrideBootstrapCommand: |
      #!/bin/bash
      source /var/lib/cloud/scripts/eksctl/bootstrap.helper.sh
      # Note "--node-labels=${NODE_LABELS}" needs the above helper sourced to work, otherwise will have to be defined manually.
      /etc/eks/bootstrap.sh ${CLUSTER_NAME} --container-runtime containerd --kubelet-extra-args "--node-labels=${NODE_LABELS}"
    desiredCapacity: 2
    amiFamily: Ubuntu2204
    ami: ami-xxxxxxxxxxxxxx
    volumeType: gp3
    volumeEncrypted: true
    #volumeSize: 96
    iam:
       attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
    ssh:
        allow: true
        publicKeyName: TestEksKeyPair
